f = open(r"E:\introflow\frontend\src\app\page.tsx", "a", encoding="utf-8")
f.write('{view==="snapshots"&&!sel&&<div><h1 style={{margin:"0 0 24px",fontSize:"24px",fontWeight:800}}>Snapshots</h1>\n')
f.write('{DATA.map(s=><Card key={s.id} style={{marginBottom:"10px",cursor:"pointer"}}><div onClick={()=>setSel(s)} style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",flexWrap:"wrap",gap:"8px"}}><div><div style={{display:"flex",alignItems:"center",gap:"8px",marginBottom:"6px"}}><span style={{fontFamily:F.mono,fontSize:"12px",color:C.t3}}>{s.id}</span><Badge state={s.state}/></div><div style={{fontSize:"16px",fontWeight:600}}>{s.introducer} - {s.target}</div><div style={{fontSize:"13px",color:C.t2,marginTop:"4px"}}>{s.purpose} - {s.value_range}</div></div><div style={{textAlign:"right"}}><div style={{fontSize:"11px",color:C.t3}}>{s.events.length} events</div></div></div></Card>)}\n')
f.write('</div>}\n')
f.write('{sel&&<Detail snap={sel} onBack={()=>setSel(null)} onAction={(a)=>notify(a+" executed")}/>}\n\n')
f.write('{view==="events"&&<div><h1 style={{margin:"0 0 4px",fontSize:"24px",fontWeight:800}}>Event Log</h1><p style={{margin:"0 0 24px",fontSize:"13px",color:C.t3}}>Immutable, append-only, hash-chained</p>\n')
f.write('<Card style={{padding:0,overflow:"hidden"}}><div style={{display:"grid",gridTemplateColumns:"90px 1fr 120px 180px",padding:"12px 20px",background:C.sfa,borderBottom:1px solid ,fontSize:"11px",fontWeight:700,color:C.t3,textTransform:"uppercase",letterSpacing:"0.06em"}}><span>Snapshot</span><span>Event</span><span>Actor</span><span>Time</span></div>\n')
f.write('{allEvents.map((e,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"90px 1fr 120px 180px",padding:"12px 20px",borderBottom:1px solid ,fontSize:"13px",alignItems:"center"}}><span style={{fontFamily:F.mono,color:C.t3,fontSize:"12px"}}>{e.sid}</span><span style={{fontWeight:600}}>{e.type.replace(/([A-Z])/g," ").trim()}</span><span style={{color:C.t2}}>{e.actor}</span><span style={{fontFamily:F.mono,color:C.t3,fontSize:"12px"}}>{new Date(e.time).toLocaleDateString()}</span></div>)}\n')
f.write('</Card></div>}\n\n')
f.close()
print("Part 10 OK")
