f = open(r"E:\introflow\frontend\src\app\page.tsx", "a", encoding="utf-8")
f.write('const STATES: Record<string,{label:string;color:string;bg:string;icon:string}> = {\n')
f.write('  SNAPSHOT_FROZEN:{label:"Frozen",color:C.inf,bg:C.ind,icon:"*"},\n')
f.write('  INTRO_CLAIMED:{label:"Claimed",color:C.pr,bg:C.prd,icon:">"},\n')
f.write('  INTRO_CONFIRMED:{label:"Confirmed",color:C.ac,bg:C.acd,icon:"+"},\n')
f.write('  OUTCOME_SUBMITTED:{label:"Pending",color:C.wr,bg:C.wrd,icon:"?"},\n')
f.write('  OUTCOME_VERIFIED_SUCCESS:{label:"Verified",color:C.ac,bg:C.acd,icon:"!"},\n')
f.write('  OUTCOME_VERIFIED_FAIL:{label:"Failed",color:C.dg,bg:C.dgd,icon:"x"},\n')
f.write('  TIMED_OUT:{label:"Timed Out",color:C.t3,bg:"rgba(113,113,122,0.12)",icon:"~"},\n')
f.write('  DISPUTED:{label:"Disputed",color:C.dg,bg:C.dgd,icon:"!"},\n')
f.write('  RESOLVED:{label:"Resolved",color:C.ac,bg:C.acd,icon:"="},\n')
f.write('};\n\n')
f.write('interface Evt {type:string;actor:string;time:string;sid?:string;id?:string;}\n')
f.write('interface Snap {id:string;state:string;introducer:string;requester:string;target:string;purpose:string;success_condition:string;value_range:string;time_window_days:number;frozen_at:string;events:Evt[];}\n\n')
f.close()
print("Part 2 OK")
