f = open(r"E:\introflow\frontend\src\app\page.tsx", "a", encoding="utf-8")
f.write('function Detail({snap,onBack,onAction}:{snap:any;onBack:()=>void;onAction:(a:string)=>void}){\n')
f.write('const st=snap.state;\n')
f.write('const tc:any={SnapshotCreated:C.inf,SnapshotFrozen:C.inf,IntroClaimed:C.pr,IntroConfirmed:C.ac,OutcomeSubmitted:C.wr,OutcomeVerifiedSuccess:C.ac,DisputeOpened:C.dg};\n')
f.write('return <div>\n')
f.write('<button onClick={onBack} style={{background:"none",border:"none",color:C.t2,cursor:"pointer",fontSize:"13px",fontFamily:F.sans,padding:0,marginBottom:"20px"}}>Back</button>\n')
f.write('<Card style={{marginBottom:"16px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",flexWrap:"wrap",gap:"12px"}}><div><div style={{display:"flex",alignItems:"center",gap:"10px",marginBottom:"6px"}}><span style={{fontFamily:F.mono,fontSize:"13px",color:C.t3}}>{snap.id}</span><Badge state={st}/></div>\n')
f.write('<h2 style={{margin:0,fontSize:"22px",fontWeight:700}}>{snap.purpose} Introduction</h2></div><div style={{fontSize:"13px",color:C.t3,fontFamily:F.mono}}>{new Date(snap.frozen_at).toLocaleDateString()}</div></div></Card>\n')
f.write('<div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:"12px",marginBottom:"16px"}}>\n')
f.write('{[{r:"Introducer",n:snap.introducer,c:C.pr},{r:"Requester",n:snap.requester,c:C.inf},{r:"Target",n:snap.target,c:C.ac}].map((p:any)=><Card key={p.r} style={{borderLeft:3px solid ,padding:"16px"}}><div style={{fontSize:"11px",color:C.t3,textTransform:"uppercase",letterSpacing:"0.06em",fontWeight:600}}>{p.r}</div><div style={{fontSize:"15px",fontWeight:600,marginTop:"4px"}}>{p.n}</div></Card>)}</div>\n')
f.close()
print("Part 5 OK")
