f = open(r"E:\introflow\frontend\src\app\page.tsx", "a", encoding="utf-8")
f.write('<Card style={{marginBottom:"16px"}}><h3 style={{margin:"0 0 12px",fontSize:"14px",fontWeight:700}}>FROZEN TERMS</h3><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr 1fr",gap:"16px"}}>{[{l:"Purpose",v:snap.purpose},{l:"Condition",v:snap.success_condition.replace(/_/g," ")},{l:"Value",v:snap.value_range},{l:"Window",v:snap.time_window_days+"d"}].map((t:any)=><div key={t.l}><div style={{fontSize:"11px",color:C.t3,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:"4px"}}>{t.l}</div><div style={{fontSize:"14px",fontWeight:500,fontFamily:F.mono}}>{t.v}</div></div>)}</div></Card>\n')
f.write('<Card style={{marginBottom:"16px"}}><h3 style={{margin:"0 0 12px",fontSize:"14px",fontWeight:700}}>ACTIONS</h3><div style={{display:"flex",flexWrap:"wrap",gap:"10px"}}>\n')
f.write('<Btn primary={st==="SNAPSHOT_FROZEN"} disabled={st!=="SNAPSHOT_FROZEN"} onClick={()=>onAction("claim")}>Claim</Btn>\n')
f.write('<Btn primary={st==="INTRO_CLAIMED"} disabled={st!=="INTRO_CLAIMED"} onClick={()=>onAction("confirm")}>Confirm</Btn>\n')
f.write('<Btn primary={st==="INTRO_CONFIRMED"} disabled={st!=="INTRO_CONFIRMED"} onClick={()=>onAction("outcome")}>Outcome</Btn>\n')
f.write('<Btn primary={st==="OUTCOME_SUBMITTED"} disabled={st!=="OUTCOME_SUBMITTED"} onClick={()=>onAction("verify")}>Verify</Btn>\n')
f.write('<Btn disabled={!["INTRO_CONFIRMED","OUTCOME_SUBMITTED"].includes(st)} onClick={()=>onAction("dispute")} style={{background:C.dgd,color:C.dg}}>Dispute</Btn>\n')
f.write('</div></Card>\n')
f.write('<Card><div style={{display:"flex",justifyContent:"space-between",marginBottom:"16px"}}><h3 style={{margin:0,fontSize:"14px",fontWeight:700}}>EVENT LOG</h3><span style={{fontSize:"12px",color:C.t3,fontFamily:F.mono}}>{snap.events.length} events</span></div>\n')
f.write('<div style={{paddingLeft:"24px",position:"relative"}}><div style={{position:"absolute",left:"7px",top:"8px",bottom:"8px",width:"2px",background:linear-gradient(to bottom, , transparent)}}/>\n')
f.write('{snap.events.map((e:any,i:number)=><div key={i} style={{position:"relative",paddingBottom:"16px"}}><div style={{position:"absolute",left:"-20px",top:"6px",width:"10px",height:"10px",borderRadius:"50%",background:tc[e.type]||C.t3}}/><div style={{fontSize:"13px",fontWeight:600,color:tc[e.type]||C.t2}}>{e.type.replace(/([A-Z])/g," ").trim()}</div><div style={{fontSize:"12px",color:C.t3,marginTop:"2px"}}>{e.actor} - {new Date(e.time).toLocaleDateString()}</div></div>)}\n')
f.write('</div></Card></div>;}\n\n')
f.close()
print("Part 6 OK")
