f = open(r"E:\introflow\frontend\src\app\page.tsx", "a", encoding="utf-8")
f.write('export default function Home(){\n')
f.write('const[view,setView]=useState("dashboard");\n')
f.write('const[sel,setSel]=useState<any>(null);\n')
f.write('const[showCreate,setShowCreate]=useState(false);\n')
f.write('const[toast,setToast]=useState<string|null>(null);\n')
f.write('const notify=useCallback((m:string)=>{setToast(m);setTimeout(()=>setToast(null),3000);},[]);\n')
f.write('const nav=(v:string)=>{setView(v);setSel(null);};\n')
f.write('const active=DATA.filter(s=>!["OUTCOME_VERIFIED_SUCCESS","OUTCOME_VERIFIED_FAIL","TIMED_OUT","RESOLVED"].includes(s.state));\n')
f.write('const completed=DATA.filter(s=>["OUTCOME_VERIFIED_SUCCESS","RESOLVED"].includes(s.state));\n')
f.write('const disputed=DATA.filter(s=>s.state==="DISPUTED");\n')
f.write('const totalEvts=DATA.reduce((a,s)=>a+s.events.length,0);\n')
f.write('const items=[{id:"dashboard",icon:"O",label:"Dashboard"},{id:"snapshots",icon:"S",label:"Snapshots"},{id:"events",icon:"E",label:"Event Log"},{id:"health",icon:"H",label:"Health"}];\n')
f.write('const allEvents=DATA.flatMap(s=>s.events.map(e=>({...e,sid:s.id}))).sort((a,b)=>new Date(b.time).getTime()-new Date(a.time).getTime());\n\n')
f.write('return <div style={{display:"flex",minHeight:"100vh",background:C.bg,fontFamily:F.sans,color:C.tx}}>\n')
f.write("<style>{@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap');*{box-sizing:border-box;margin:0;padding:0}body{margin:0;background:}::-webkit-scrollbar{width:6px}::-webkit-scrollbar-thumb{background:;border-radius:3px}}</style>\n")
f.close()
print("Part 7 OK")
